In [3]:
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [4]:
df_accepted = pd.read_csv("accepted.csv")
# df_rejected = pd.read_csv("rejected.csv")

/Users/carterpace/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
print(df_accepted.info())
# print(df_rejected.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Columns: 151 entries, id to settlement_term
dtypes: float64(113), object(38)
memory usage: 2.5+ GB
None

In [9]:
cwp = df_accepted[['home_ownership',
                    'id',
                    'il_util',
                    'initial_list_status',
                    'inq_fi',
                    'inq_last_12m',
                    'inq_last_6mths',
                    'installment',
                    'int_rate',
                    'issue_d',
                    'last_credit_pull_d',
                    'last_fico_range_high',
                    'last_fico_range_low',
                    'last_pymnt_amnt',
                    'last_pymnt_d',
                    'loan_amnt',
                    'loan_status',
                    'max_bal_bc',
                    'member_id',
                    'mo_sin_old_il_acct',
                    'mo_sin_old_rev_tl_op',
                    'mo_sin_rcnt_rev_tl_op',
                    'mo_sin_rcnt_tl',
                    'mort_acc',
                    'mths_since_last_delinq',
                   'mths_since_last_major_derog']]
# cwp = df_accepted.iloc[:,27:54]

# df = df_accepted[['loan_amnt', 'fico_range_high']]

  home_ownership        id  il_util initial_list_status  inq_fi  inq_last_12m  \
0       MORTGAGE  68407277     36.0                   w     3.0           4.0
1       MORTGAGE  68355089     73.0                   w     0.0           6.0
2       MORTGAGE  68341763     73.0                   w     2.0           1.0
3       MORTGAGE  66310712     70.0                   w     0.0           0.0
4       MORTGAGE  68476807     84.0                   w     2.0           3.0

   inq_last_6mths  installment  int_rate   issue_d  \
0             1.0       123.03     13.99  Dec-2015
1             4.0       820.28     11.99  Dec-2015
2             0.0       432.66     10.78  Dec-2015
3             0.0       829.90     14.85  Dec-2015
4             3.0       289.91     22.45  Dec-2015

              ...              loan_status  max_bal_bc  member_id  \
0             ...               Fully Paid       722.0        NaN
1             ...               Fully Paid      6472.0        NaN
2             ...               Fully Paid      2081.0        NaN
3             ...                  Current      6987.0        NaN
4             ...               Fully Paid      9702.0        NaN

   mo_sin_old_il_acct mo_sin_old_rev_tl_op  mo_sin_rcnt_rev_tl_op  \
0               148.0                128.0                    3.0
1               113.0                192.0                    2.0
2               125.0                184.0                   14.0
3                36.0                 87.0                    2.0
4               128.0                210.0                    4.0

  mo_sin_rcnt_tl  mort_acc  mths_since_last_delinq  \
0            3.0       1.0                    30.0
1            2.0       4.0                     6.0
2           14.0       5.0                     NaN
3            2.0       1.0                     NaN
4            4.0       6.0                    12.0

   mths_since_last_major_derog
0                         30.0
1                          NaN
2                          NaN
3                          NaN
4                          NaN

[5 rows x 26 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 26 columns):
home_ownership                 object
id                             object
il_util                        float64
initial_list_status            object
inq_fi                         float64
inq_last_12m                   float64
inq_last_6mths                 float64
installment                    float64
int_rate                       float64
issue_d                        object
last_credit_pull_d             object
last_fico_range_high           float64
last_fico_range_low            float64
last_pymnt_amnt                float64
last_pymnt_d                   object
loan_amnt                      float64
loan_status                    object
max_bal_bc                     float64
member_id                      float64
mo_sin_old_il_acct             float64
mo_sin_old_rev_tl_op           float64
mo_sin_rcnt_rev_tl_op          float64
mo_sin_rcnt_tl                 float64
mort_acc                       float64
mths_since_last_delinq         float64
mths_since_last_major_derog    float64
dtypes: float64(19), object(7)
memory usage: 448.4+ MB
None
            il_util        inq_fi  inq_last_12m  inq_last_6mths   installment  \
count  1.191818e+06  1.394539e+06  1.394538e+06    2.260638e+06  2.260668e+06
mean   6.914098e+01  1.012867e+00  2.036667e+00    5.768354e-01  4.458068e+02
std    2.374839e+01  1.489456e+00  2.383117e+00    8.859632e-01  2.671735e+02
min    0.000000e+00  0.000000e+00  0.000000e+00    0.000000e+00  4.930000e+00
25%    5.500000e+01  0.000000e+00  0.000000e+00    0.000000e+00  2.516500e+02
50%    7.200000e+01  1.000000e+00  1.000000e+00    0.000000e+00  3.779900e+02
75%    8.600000e+01  1.000000e+00  3.000000e+00    1.000000e+00  5.933200e+02
max    1.000000e+03  4.800000e+01  6.700000e+01    3.300000e+01  1.719830e+03

           int_rate  last_fico_range_high  last_fico_range_low  \
count  2.260668e+06          2.260668e+06         2.260668e+06
mean   1.309283e+01          6.876610e+02         6.755397e+02
std    4.832138e+00          7.297044e+01         1.110976e+02
min    5.310000e+00          0.000000e+00         0.000000e+00
25%    9.490000e+00          6.540000e+02         6.500000e+02
50%    1.262000e+01          6.990000e+02         6.950000e+02
75%    1.599000e+01          7.340000e+02         7.300000e+02
max    3.099000e+01          8.500000e+02         8.450000e+02

       last_pymnt_amnt     loan_amnt    max_bal_bc  member_id  \
count     2.260668e+06  2.260668e+06  1.394539e+06        0.0
mean      3.429346e+03  1.504693e+04  5.806393e+03        NaN
std       6.018248e+03  9.190245e+03  5.690561e+03        NaN
min       0.000000e+00  5.000000e+02  0.000000e+00        NaN
25%       3.103300e+02  8.000000e+03  2.284000e+03        NaN
50%       6.005700e+02  1.290000e+04  4.413000e+03        NaN
75%       3.743750e+03  2.000000e+04  7.598000e+03        NaN
max       4.219205e+04  4.000000e+04  1.170668e+06        NaN

       mo_sin_old_il_acct  mo_sin_old_rev_tl_op  mo_sin_rcnt_rev_tl_op  \
count        2.121597e+06          2.190391e+06           2.190391e+06
mean         1.257378e+02          1.814916e+02           1.402409e+01
std          5.338218e+01          9.711845e+01           1.753308e+01
min          0.000000e+00          1.000000e+00           0.000000e+00
25%          9.600000e+01          1.160000e+02           4.000000e+00
50%          1.300000e+02          1.640000e+02           8.000000e+00
75%          1.540000e+02          2.320000e+02           1.700000e+01
max          9.990000e+02          9.990000e+02           5.470000e+02

       mo_sin_rcnt_tl      mort_acc  mths_since_last_delinq  \
count    2.190392e+06  2.210638e+06            1.102166e+06
mean     8.297469e+00  1.555382e+00            3.454092e+01
std      9.208557e+00  1.904981e+00            2.190047e+01
min      0.000000e+00  0.000000e+00            0.000000e+00
25%      3.000000e+00  0.000000e+00            1.600000e+01
50%      6.000000e+00  1.000000e+00            3.100000e+01
75%      1.100000e+01  3.000000e+00            5.000000e+01
max      3.820000e+02  9.400000e+01            2.260000e+02

       mths_since_last_major_derog
count                580775.000000
mean                     44.164220
std                      21.533121
min                       0.000000
25%                      27.000000
50%                      44.000000
75%                      62.000000
max                     226.000000

In [11]:
cwp.head()

,home_ownership,id,il_util,initial_list_status,inq_fi,inq_last_12m,inq_last_6mths,installment,int_rate,issue_d,...,loan_status,max_bal_bc,member_id,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_last_delinq,mths_since_last_major_derog
0,MORTGAGE,68407277,36.0,w,3.0,4.0,1.0,123.03,13.99,Dec-2015,...,Fully Paid,722.0,NaN,148.0,128.0,3.0,3.0,1.0,30.0,30.0
1,MORTGAGE,68355089,73.0,w,0.0,6.0,4.0,820.28,11.99,Dec-2015,...,Fully Paid,6472.0,NaN,113.0,192.0,2.0,2.0,4.0,6.0,NaN
2,MORTGAGE,68341763,73.0,w,2.0,1.0,0.0,432.66,10.78,Dec-2015,...,Fully Paid,2081.0,NaN,125.0,184.0,14.0,14.0,5.0,NaN,NaN
3,MORTGAGE,66310712,70.0,w,0.0,0.0,0.0,829.90,14.85,Dec-2015,...,Current,6987.0,NaN,36.0,87.0,2.0,2.0,1.0,NaN,NaN
4,MORTGAGE,68476807,84.0,w,2.0,3.0,3.0,289.91,22.45,Dec-2015,...,Fully Paid,9702.0,NaN,128.0,210.0,4.0,4.0,6.0,12.0,NaN

In [12]:
cwp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 26 columns):
home_ownership                 object
id                             object
il_util                        float64
initial_list_status            object
inq_fi                         float64
inq_last_12m                   float64
inq_last_6mths                 float64
installment                    float64
int_rate                       float64
issue_d                        object
last_credit_pull_d             object
last_fico_range_high           float64
last_fico_range_low            float64
last_pymnt_amnt                float64
last_pymnt_d                   object
loan_amnt                      float64
loan_status                    object
max_bal_bc                     float64
member_id                      float64
mo_sin_old_il_acct             float64
mo_sin_old_rev_tl_op           float64
mo_sin_rcnt_rev_tl_op          float64
mo_sin_rcnt_tl                 float64
mort_acc                       float64
mths_since_last_delinq         float64
mths_since_last_major_derog    float64
dtypes: float64(19), object(7)
memory usage: 448.4+ MB

In [13]:
cwp.describe()

,il_util,inq_fi,inq_last_12m,inq_last_6mths,installment,int_rate,last_fico_range_high,last_fico_range_low,last_pymnt_amnt,loan_amnt,max_bal_bc,member_id,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_last_delinq,mths_since_last_major_derog
count,1.191818e+06,1.394539e+06,1.394538e+06,2.260638e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,1.394539e+06,0.0,2.121597e+06,2.190391e+06,2.190391e+06,2.190392e+06,2.210638e+06,1.102166e+06,580775.000000
mean,6.914098e+01,1.012867e+00,2.036667e+00,5.768354e-01,4.458068e+02,1.309283e+01,6.876610e+02,6.755397e+02,3.429346e+03,1.504693e+04,5.806393e+03,NaN,1.257378e+02,1.814916e+02,1.402409e+01,8.297469e+00,1.555382e+00,3.454092e+01,44.164220
std,2.374839e+01,1.489456e+00,2.383117e+00,8.859632e-01,2.671735e+02,4.832138e+00,7.297044e+01,1.110976e+02,6.018248e+03,9.190245e+03,5.690561e+03,NaN,5.338218e+01,9.711845e+01,1.753308e+01,9.208557e+00,1.904981e+00,2.190047e+01,21.533121
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.930000e+00,5.310000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+02,0.000000e+00,NaN,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,5.500000e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.516500e+02,9.490000e+00,6.540000e+02,6.500000e+02,3.103300e+02,8.000000e+03,2.284000e+03,NaN,9.600000e+01,1.160000e+02,4.000000e+00,3.000000e+00,0.000000e+00,1.600000e+01,27.000000
50%,7.200000e+01,1.000000e+00,1.000000e+00,0.000000e+00,3.779900e+02,1.262000e+01,6.990000e+02,6.950000e+02,6.005700e+02,1.290000e+04,4.413000e+03,NaN,1.300000e+02,1.640000e+02,8.000000e+00,6.000000e+00,1.000000e+00,3.100000e+01,44.000000
75%,8.600000e+01,1.000000e+00,3.000000e+00,1.000000e+00,5.933200e+02,1.599000e+01,7.340000e+02,7.300000e+02,3.743750e+03,2.000000e+04,7.598000e+03,NaN,1.540000e+02,2.320000e+02,1.700000e+01,1.100000e+01,3.000000e+00,5.000000e+01,62.000000
max,1.000000e+03,4.800000e+01,6.700000e+01,3.300000e+01,1.719830e+03,3.099000e+01,8.500000e+02,8.450000e+02,4.219205e+04,4.000000e+04,1.170668e+06,NaN,9.990000e+02,9.990000e+02,5.470000e+02,3.820000e+02,9.400000e+01,2.260000e+02,226.000000

In [20]:
categorical_vars = ['home_ownership', 'initial_list_status', 'loan_status']
numerical_vars = ['il_util',
                    'initial_list_status',
                    'inq_fi',
                    'inq_last_12m',
                    'inq_last_6mths',
                    'installment',
                    'int_rate',
                    'issue_d',
                    'last_credit_pull_d',
                    'last_fico_range_high',
                    'last_fico_range_low',
                    'last_pymnt_amnt',
                    'last_pymnt_d',
                    'loan_amnt',
                    'loan_status',
                    'max_bal_bc',
                    'member_id',
                    'mo_sin_old_il_acct',
                    'mo_sin_old_rev_tl_op',
                    'mo_sin_rcnt_rev_tl_op',
                    'mo_sin_rcnt_tl',
                    'mort_acc',
                    'mths_since_last_delinq',
                   'mths_since_last_major_derog']

print(cwp.loan_status)

0           Fully Paid
1           Fully Paid
2           Fully Paid
3              Current
4           Fully Paid
5           Fully Paid
6           Fully Paid
7           Fully Paid
8           Fully Paid
9           Fully Paid
10             Current
11             Current
12          Fully Paid
13         Charged Off
14          Fully Paid
15          Fully Paid
16          Fully Paid
17          Fully Paid
18             Current
19          Fully Paid
20          Fully Paid
21          Fully Paid
22          Fully Paid
23          Fully Paid
24          Fully Paid
25         Charged Off
26          Fully Paid
27          Fully Paid
28          Fully Paid
29          Fully Paid
              ...
2260671        Current
2260672    Charged Off
2260673    Charged Off
2260674     Fully Paid
2260675     Fully Paid
2260676        Current
2260677    Charged Off
2260678        Current
2260679        Current
2260680     Fully Paid
2260681        Current
2260682        Current
2260683        Current
2260684     Fully Paid
2260685    Charged Off
2260686     Fully Paid
2260687        Current
2260688     Fully Paid
2260689        Current
2260690     Fully Paid
2260691    Charged Off
2260692     Fully Paid
2260693        Current
2260694        Current
2260695        Current
2260696        Current
2260697    Charged Off
2260698        Current
2260699            NaN
2260700            NaN
Name: loan_status, Length: 2260701, dtype: object

In [21]:
df = df_accepted

In [25]:
df.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object', length=151)

In [26]:
total_num = df.isnull().sum().sort_values(ascending=False)

In [27]:
perc = df.isnull().sum()/df.isnull().count() *100
perc1 = (round(perc,2).sort_values(ascending=False))

# Creating a data frame:
df_miss = pd.concat([total_num, perc1], axis =1 , keys =["Total Missing Values", "Percentage %"]).sort_values(by ="Percentage %", ascending = False)

/Users/carterpace/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """

In [45]:
top_mis = df_miss[df_miss["Percentage %"]<10]
top_mis.reset_index(inplace=True)
vals = list(top_mis['index'])

In [47]:
df = df[vals]

In [48]:
num_feat = df.select_dtypes('number').columns.values
df[num_feat].nunique().sort_values()

policy_code                         1
num_tl_30dpd                        5
num_tl_120dpd_2m                    7
acc_now_delinq                      9
chargeoff_within_12_mths           11
pub_rec_bankruptcies               12
collections_12_mths_ex_med         16
inq_last_6mths                     28
num_tl_op_past_12m                 33
num_tl_90g_dpd_24m                 34
delinq_2yrs                        37
num_actv_bc_tl                     42
tax_liens                          42
pub_rec                            43
num_accts_ever_120_pd              44
mort_acc                           47
fico_range_high                    48
fico_range_low                     48
num_rev_tl_bal_gt_0                50
acc_open_past_24mths               57
num_actv_rev_tl                    57
num_bc_sats                        60
last_fico_range_low                71
last_fico_range_high               72
num_bc_tl                          76
num_op_rev_tl                      81
num_sats                           91
open_acc                           91
num_rev_accts                     117
num_il_tl                         122
                               ...
mo_sin_old_rev_tl_op              787
revol_util                       1430
bc_util                          1494
loan_amnt                        1572
funded_amnt                      1572
delinq_amnt                      2617
funded_amnt_inv                 10057
dti                             10845
tot_coll_amt                    15574
total_rec_late_fee              18375
total_bc_limit                  20309
total_rev_hi_lim                34220
avg_cur_bal                     88597
annual_inc                      89368
bc_open_to_buy                  91500
installment                     93301
revol_bal                      102251
recoveries                     132777
collection_recovery_fee        146222
total_il_high_credit_limit     194137
total_bal_ex_mort              212777
out_prncp                      356141
out_prncp_inv                  368481
total_rec_prncp                486463
tot_cur_bal                    487688
tot_hi_cred_lim                529972
total_rec_int                  635921
last_pymnt_amnt                704467
total_pymnt_inv               1311099
total_pymnt                   1633857
Length: 68, dtype: int64

In [64]:
df2 = df.dropna()
df2.shape

(1852324, 92)

In [66]:
import numpy as np
from itertools import combinations
from scipy.stats import pearsonr

num_feat = df2.select_dtypes('number').columns.values
comb_num_feat = np.array(list(combinations(num_feat, 2)))
corr_num_feat = np.array([])
for comb in comb_num_feat:
    corr = pearsonr(df2[comb[0]], df2[comb[1]])[0]
    corr_num_feat = np.append(corr_num_feat, corr)

/Users/carterpace/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:3010: RuntimeWarning: invalid value encountered in double_scalars
  r = r_num / r_den

In [67]:
corr_num_feat

array([ 0.00596281, -0.00790066, -0.0080264 , ...,  0.84910194,
       -0.27986844, -0.35507335])

In [68]:
high_corr_num = comb_num_feat[np.abs(corr_num_feat) >= 0.9]
high_corr_num

/Users/carterpace/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater_equal
  """Entry point for launching an IPython kernel.

array([['num_rev_tl_bal_gt_0', 'num_actv_rev_tl'],
       ['tot_cur_bal', 'tot_hi_cred_lim'],
       ['num_sats', 'open_acc'],
       ['total_pymnt', 'total_pymnt_inv'],
       ['total_pymnt', 'total_rec_prncp'],
       ['total_pymnt_inv', 'total_rec_prncp'],
       ['funded_amnt_inv', 'funded_amnt'],
       ['funded_amnt_inv', 'installment'],
       ['funded_amnt_inv', 'loan_amnt'],
       ['funded_amnt', 'installment'],
       ['funded_amnt', 'loan_amnt'],
       ['fico_range_low', 'fico_range_high'],
       ['recoveries', 'collection_recovery_fee'],
       ['installment', 'loan_amnt'],
       ['out_prncp_inv', 'out_prncp']], dtype='<U26')

In [69]:
df3 = df2.drop(np.unique(high_corr_num[:, 0]), axis=1, errors='ignore')
df3.shape

(1852324, 81)

In [73]:
df3

,emp_title,num_tl_120dpd_2m,emp_length,mo_sin_old_il_acct,bc_util,percent_bc_gt_75,bc_open_to_buy,mths_since_recent_bc,pct_tl_nvr_dlq,num_il_tl,...,open_acc,loan_status,loan_amnt,last_pymnt_amnt,last_fico_range_low,last_fico_range_high,last_credit_pull_d,issue_d,int_rate,zip_code
0,leadman,0.0,10+ years,148.0,37.2,0.0,1506.0,4.0,76.9,3.0,...,7.0,Fully Paid,3600.0,122.67,560.0,564.0,Mar-2019,Dec-2015,13.99,190xx
1,Engineer,0.0,10+ years,113.0,27.1,7.7,57830.0,2.0,97.4,6.0,...,22.0,Fully Paid,24700.0,926.35,695.0,699.0,Mar-2019,Dec-2015,11.99,577xx
3,Information Systems Officer,0.0,10+ years,36.0,12.1,0.0,54962.0,2.0,100.0,2.0,...,13.0,Current,35000.0,829.90,675.0,679.0,Mar-2019,Dec-2015,14.85,076xx
4,Contract Specialist,0.0,3 years,128.0,77.5,60.0,4567.0,4.0,96.6,10.0,...,12.0,Fully Paid,10400.0,10128.96,700.0,704.0,Mar-2018,Dec-2015,22.45,174xx
5,Veterinary Tecnician,0.0,4 years,338.0,91.0,100.0,844.0,36.0,100.0,2.0,...,5.0,Fully Paid,11950.0,7653.56,755.0,759.0,May-2017,Dec-2015,13.44,300xx
6,Vice President of Recruiting Operations,0.0,10+ years,142.0,102.9,100.0,0.0,12.0,96.3,7.0,...,12.0,Fully Paid,20000.0,15681.05,650.0,654.0,Mar-2019,Dec-2015,9.17,550xx
7,road driver,0.0,10+ years,149.0,5.7,0.0,13674.0,32.0,93.3,9.0,...,8.0,Fully Paid,20000.0,14618.23,670.0,674.0,Mar-2019,Dec-2015,8.49,293xx
8,SERVICE MANAGER,0.0,6 years,164.0,50.1,28.6,8182.0,4.0,95.7,3.0,...,14.0,Fully Paid,10000.0,1814.48,715.0,719.0,Mar-2019,Dec-2015,6.49,160xx
9,Vendor liaison,0.0,10+ years,155.0,41.4,33.3,9966.0,50.0,94.4,5.0,...,8.0,Fully Paid,8000.0,4996.24,675.0,679.0,Nov-2018,Dec-2015,11.48,029xx
10,Executive Director,0.0,6 years,150.0,39.9,25.0,12617.0,1.0,97.0,15.0,...,16.0,Current,22400.0,508.30,585.0,589.0,Mar-2019,Dec-2015,12.88,290xx
11,Senior Structural Designer,0.0,1 year,147.0,61.0,60.0,17922.0,9.0,100.0,6.0,...,13.0,Current,16000.0,363.07,750.0,754.0,Mar-2019,Dec-2015,12.88,786xx
13,Software Manager,0.0,7 years,115.0,51.3,14.3,5128.0,9.0,100.0,6.0,...,18.0,Charged Off,18000.0,471.70,580.0,584.0,Nov-2017,Dec-2015,19.48,916xx
14,Senior Manager,0.0,10+ years,82.0,59.9,22.2,16623.0,19.0,91.7,4.0,...,16.0,Fully Paid,28000.0,17093.51,760.0,764.0,Mar-2019,Dec-2015,6.49,275xx
15,tech,0.0,8 years,234.0,61.8,66.7,4778.0,11.0,100.0,5.0,...,7.0,Fully Paid,9600.0,3480.17,775.0,779.0,Aug-2018,Dec-2015,7.49,299xx
16,Sales Manager,0.0,10+ years,142.0,54.3,20.0,17538.0,13.0,100.0,7.0,...,9.0,Fully Paid,25000.0,20807.39,720.0,724.0,Apr-2017,Dec-2015,7.49,226xx
17,GS-11,0.0,10+ years,109.0,16.7,0.0,60336.0,1.0,100.0,6.0,...,17.0,Fully Paid,18000.0,18004.90,790.0,794.0,Mar-2019,Dec-2015,11.99,856xx
18,Teacher,0.0,5 years,163.0,60.5,14.3,15603.0,12.0,87.9,14.0,...,21.0,Current,23000.0,471.77,740.0,744.0,Mar-2019,Dec-2015,8.49,117xx
20,Corporate Insurance,0.0,10+ years,114.0,45.9,25.0,18383.0,5.0,100.0,8.0,...,15.0,Fully Paid,29900.0,25234.24,715.0,719.0,Jan-2018,Dec-2015,12.88,219xx
21,Bookkeeper/Accounting,0.0,10+ years,131.0,17.6,0.0,263953.0,11.0,78.9,6.0,...,11.0,Fully Paid,16000.0,12322.68,660.0,664.0,Sep-2017,Dec-2015,14.85,297xx
22,Director of Product Development,0.0,2 years,113.0,63.4,40.0,10607.0,22.0,100.0,3.0,...,6.0,Fully Paid,28000.0,12486.30,740.0,744.0,Mar-2019,Dec-2015,13.44,100xx
23,General Manager,0.0,2 years,50.0,101.4,100.0,0.0,36.0,100.0,3.0,...,3.0,Fully Paid,5000.0,169.17,655.0,659.0,Mar-2019,Dec-2015,13.44,214xx
24,Analyst,0.0,10+ years,124.0,88.5,50.0,437.0,36.0,93.7,4.0,...,9.0,Fully Paid,6000.0,186.60,715.0,719.0,Mar-2019,Dec-2015,7.49,750xx
25,mechanic,0.0,5 years,47.0,14.1,0.0,2233.0,26.0,66.7,1.0,...,6.0,Charged Off,4225.0,146.16,0.0,499.0,Dec-2017,Dec-2015,14.85,672xx
26,driver,0.0,9 years,63.0,3.0,0.0,73931.0,19.0,100.0,4.0,...,12.0,Fully Paid,20000.0,3577.50,805.0,809.0,Aug-2018,Dec-2015,5.32,125xx
27,Professional Sales Associate,0.0,< 1 year,149.0,100.8,100.0,0.0,13.0,100.0,10.0,...,11.0,Fully Paid,16000.0,15481.30,675.0,679.0,Jul-2016,Dec-2015,17.97,880xx
28,Network Security Specialist III,0.0,< 1 year,160.0,51.7,0.0,11397.0,37.0,100.0,24.0,...,20.0,Fully Paid,17600.0,17.88,775.0,779.0,Aug-2018,Dec-2015,5.32,672xx
29,DEPUTY SHERIFF,0.0,10+ years,141.0,51.0,0.0,7011.0,34.0,90.5,5.0,...,7.0,Fully Paid,15000.0,455.59,690.0,694.0,Jan-2019,Dec-2015,5.32,238xx
30,"Owner, Fee Appraiser",0.0,10+ years,256.0,21.6,0.0,3684.0,1.0,80.0,12.0,...,7.0,Charged Off,16000.0,565.09,625.0,629.0,Mar-2019,Dec-2015,12.88,354xx
32,Public Affairs Specialist,0.0,1 year,147.0,83.9,66.7,3884.0,9.0,87.2,17.0,...,15.0,Fully Paid,12000.0,7884.96,750.0,754.0,Jun-2017,Dec-2015,10.78,993xx
33,Executive Assistant,0.0,9 years,124.0,21.4,0.0,57049.0,2.0,100.0,15.0,...,33.0,Charged Off,25000.0,581.58,600.0,604.0,Mar-2019,Dec-2015,13.99,212xx
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2260660,AP Manager,0.0,1 year,95.0,69.9,60.0,7457.0,47.0,100.0,13.0,...,22.0,Current,30000.0,705.70,705.0,709.0,Mar-2019,Oct-2016,14.49,600xx
2260661,Supervisor,0.0,10+ years,121.0,51.0,0.0,6131.0,22.0,97.4,13.0,...,16.0,Fully Paid,11200.0,0.41,680.0,684.0,Apr-2018,Oct-2016,13.99,400xx
2260662,OR TECH,0.0,9 years,103.0,51.8,22.2,28382.0,25.0,100.0,12.0,...,20.0,Current,24000.0,558.32,690.0,694.0,Mar-2019,Oct-2016,13.99,071xx
2260663,Service technician,0.0,10+ years,150.0,47.9,33.3,9269.0,11.0,95.2,6.0,...,8.0,Fully Paid,30000.0,23742.19,715.0,719.0,Mar-2018,Oct-2016,10.49,060xx
2260664,owner,0.0,10+ years,54.0,86.0,60.0,20829.0,40.0,100.0,1.0,...,7.0,Current,25000.0,518.84,680.0,684.0,Mar-2019,Oct-2016,8.99,606xx
2260665,Director of Distribution,0.0,10+ years,104.0,63.1,50.0,3730.0,51.0,100.0,5.0,...,17.0,Current,40000.0,920.19,700.0,704.0,Mar-2019,Oct-2016,13.49,270xx
2260666,driver,0.0,10+ years,66.0,70.8,50.0,3848.0,18.0,100.0,12.0,...,20.0,Charged Off,22400.0,515.31,600.0,604.0,Feb-2019,Oct-2016,13.49,052xx
2260667,Clinical Applications Specialist,0.0,< 1 year,171.0,68.7,40.0,3970.0,28.0,95.5,9.0,...,10.0,Fully Paid,19400.0,12594.45,715.0,719.0,Mar-2019,Oct-2016,14.49,851xx
2260668,Pilot,0.0,3 years,158.0,56.5,16.7,10967.0,5.0,77.4,23.0,...,11.0,Current,16000.0,372.21,695.0,699.0,Mar-2019,Oct-2016,13.99,973xx
2260670,Technical Resource Manager,0.0,7 years,232.0,69.3,33.3,2638.0,15.0,96.7,20.0,...,13.0,Current,20000.0,482.02,640.0,644.0,Mar-2019,Oct-2016,15.59,800xx
2260671,System Analyst,0.0,2 years,155.0,33.1,11.1,27892.0,13.0,100.0,12.0,...,21.0,Current,24000.0,527.71,725.0,729.0,Mar-2019,Oct-2016,11.49,461xx
2260672,Area Director,0.0,10+ years,16.0,39.2,33.3,42250.0,0.0,78.3,1.0,...,14.0,Charged Off,38000.0,874.18,605.0,609.0,Mar-2019,Oct-2016,13.49,101xx
2260673,Assistant Director,0.0,10+ years,124.0,43.6,25.0,53336.0,3.0,97.3,14.0,...,15.0,Charged Off,32000.0,744.42,535.0,539.0,Jun-2017,Oct-2016,13.99,799xx
2260674,Registered Nurse,0.0,9 years,137.0,79.7,80.0,2454.0,18.0,89.5,7.0,...,11.0,Fully Paid,20000.0,15305.24,700.0,704.0,Mar-2019,Oct-2016,15.59,950xx
2260675,sanitation worker,0.0,10+ years,149.0,6.7,0.0,57667.0,4.0,100.0,6.0,...,21.0,Fully Paid,16000.0,5236.72,735.0,739.0,Nov-2018,Oct-2016,10.99,112xx
2260676,Manager,0.0,10+ years,99.0,94.8,100.0,429.0,34.0,100.0,5.0,...,6.0,Current,32000.0,752.74,675.0,679.0,Mar-2019,Oct-2016,14.49,956xx
2260677,Sr. Photo Producer,0.0,5 years,269.0,57.7,33.3,6720.0,3.0,92.9,5.0,...,7.0,Charged Off,11200.0,257.66,0.0,499.0,Mar-2019,Oct-2016,13.49,981xx
2260678,Group Operations Manager,0.0,10+ years,168.0,84.1,66.7,3157.0,61.0,100.0,8.0,...,8.0,Current,36000.0,782.55,710.0,714.0,Mar-2019,Oct-2016,10.99,241xx
2260680,Sr. Project Manager,0.0,< 1 year,104.0,8.9,0.0,107774.0,16.0,100.0,12.0,...,19.0,Fully Paid,40000.0,39283.94,775.0,779.0,Mar-2019,Oct-2016,15.59,114xx
2260682,Fire Lieutenant,0.0,10+ years,119.0,80.4,66.7,5776.0,82.0,91.4,8.0,...,14.0,Current,30000.0,697.90,715.0,719.0,Mar-2019,Oct-2016,13.99,060xx
2260684,Billing clerk,0.0,8 years,151.0,26.7,50.0,57649.0,10.0,100.0,3.0,...,24.0,Fully Paid,15000.0,12991.92,720.0,724.0,Jun-2018,Oct-2016,10.49,802xx
2260686,Exec Dir Internal Audit,0.0,10+ years,139.0,90.1,100.0,6097.0,49.0,100.0,10.0,...,13.0,Fully Paid,23800.0,16846.53,675.0,679.0,Nov-2018,Oct-2016,14.49,441xx
2260687,Purchasing Manager,0.0,2 years,193.0,51.5,42.9,15281.0,30.0,100.0,32.0,...,22.0,Current,28000.0,581.10,680.0,684.0,Mar-2019,Oct-2016,8.99,857xx
2260689,Financial Advisor,0.0,5 years,124.0,63.8,60.0,29373.0,124.0,100.0,6.0,...,7.0,Current,40000.0,859.56,835.0,839.0,Mar-2019,Oct-2016,10.49,325xx
2260690,Chief Operating Officer,0.0,9 years,145.0,69.4,42.9,8427.0,70.0,100.0,17.0,...,16.0,Fully Paid,29400.0,22192.81,715.0,719.0,Jul-2018,Oct-2016,13.99,900xx
2260691,Sales Manager,0.0,3 years,53.0,10.6,0.0,14118.0,4.0,100.0,4.0,...,14.0,Charged Off,32000.0,752.74,0.0,499.0,Dec-2018,Oct-2016,14.49,863xx
2260692,Manager,0.0,10+ years,147.0,73.1,50.0,2720.0,17.0,92.0,15.0,...,12.0,Fully Paid,16000.0,12874.54,680.0,684.0,Mar-2019,Oct-2016,12.79,284xx
2260693,Current Operations Officer,0.0,4 years,44.0,21.6,0.0,73489.0,0.0,100.0,1.0,...,15.0,Current,24000.0,515.74,735.0,739.0,Mar-2019,Oct-2016,10.49,967xx
2260695,Database Administrator,0.0,10+ years,166.0,45.1,42.9,15307.0,15.0,75.9,17.0,...,24.0,Current,24000.0,515.74,730.0,734.0,Mar-2019,Oct-2016,10.49,840xx
2260697,Program Manager,0.0,6 years,132.0,77.5,40.0,4660.0,9.0,96.2,4.0,...,10.0,Charged Off,24000.0,564.56,590.0,594.0,Mar-2019,Oct-2016,14.49,334xx

In [76]:
# df3.info()
df.describe()

,num_tl_120dpd_2m,mo_sin_old_il_acct,bc_util,percent_bc_gt_75,bc_open_to_buy,mths_since_recent_bc,pct_tl_nvr_dlq,num_il_tl,num_tl_30dpd,num_op_rev_tl,...,pub_rec,policy_code,out_prncp_inv,out_prncp,open_acc,loan_amnt,last_pymnt_amnt,last_fico_range_low,last_fico_range_high,int_rate
count,2.107011e+06,2.121597e+06,2.184597e+06,2.185289e+06,2.185733e+06,2.187256e+06,2.190237e+06,2.190392e+06,2.190392e+06,2.190392e+06,...,2.260639e+06,2260668.0,2.260668e+06,2.260668e+06,2.260639e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06
mean,6.373958e-04,1.257378e+02,5.789995e+01,4.243513e+01,1.139426e+04,2.484485e+01,9.411458e+01,8.413439e+00,2.813652e-03,8.246523e+00,...,1.975278e-01,1.0,4.205965e+03,4.206891e+03,1.161240e+01,1.504693e+04,3.429346e+03,6.755397e+02,6.876610e+02,1.309283e+01
std,2.710643e-02,5.338218e+01,2.858347e+01,3.621616e+01,1.659953e+04,3.231925e+01,9.036140e+00,7.359114e+00,5.616522e-02,4.683928e+00,...,5.705150e-01,0.0,7.342333e+03,7.343239e+03,5.640861e+00,9.190245e+03,6.018248e+03,1.110976e+02,7.297044e+01,4.832138e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,1.0,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+02,0.000000e+00,0.000000e+00,0.000000e+00,5.310000e+00
25%,0.000000e+00,9.600000e+01,3.540000e+01,0.000000e+00,1.722000e+03,6.000000e+00,9.130000e+01,3.000000e+00,0.000000e+00,5.000000e+00,...,0.000000e+00,1.0,0.000000e+00,0.000000e+00,8.000000e+00,8.000000e+03,3.103300e+02,6.500000e+02,6.540000e+02,9.490000e+00
50%,0.000000e+00,1.300000e+02,6.020000e+01,3.750000e+01,5.442000e+03,1.400000e+01,1.000000e+02,6.000000e+00,0.000000e+00,7.000000e+00,...,0.000000e+00,1.0,0.000000e+00,0.000000e+00,1.100000e+01,1.290000e+04,6.005700e+02,6.950000e+02,6.990000e+02,1.262000e+01
75%,0.000000e+00,1.540000e+02,8.310000e+01,7.140000e+01,1.418700e+04,3.000000e+01,1.000000e+02,1.100000e+01,0.000000e+00,1.000000e+01,...,0.000000e+00,1.0,6.146310e+03,6.149940e+03,1.400000e+01,2.000000e+04,3.743750e+03,7.300000e+02,7.340000e+02,1.599000e+01
max,7.000000e+00,9.990000e+02,3.396000e+02,1.000000e+02,7.111400e+05,6.610000e+02,1.000000e+02,1.590000e+02,4.000000e+00,9.100000e+01,...,8.600000e+01,1.0,4.000000e+04,4.000000e+04,1.010000e+02,4.000000e+04,4.219205e+04,8.450000e+02,8.500000e+02,3.099000e+01

In [ ]:
# df3.drop(['emp_title', ])