In [1]:
# import some libraries that you will need for this step
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

#2 import the data file
data_train = pd.read_csv("accepted_2007_to_2018Q4.csv",error_bad_lines=False) # parse to a Pandas DataFrame using pd.read_csv()

#3a Print the features --> What do you observe?
print(data_train.info())

#3b Output the first 10 rows --> What do you observe?
data_train.head(10)

C:\Users\Cecilia_Z\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Columns: 151 entries, id to settlement_term
dtypes: float64(113), object(38)
memory usage: 2.5+ GB
None

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
5,68426831,NaN,11950.0,11950.0,11950.0,36 months,13.44,405.18,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
6,68476668,NaN,20000.0,20000.0,20000.0,36 months,9.17,637.58,B,B2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
7,67275481,NaN,20000.0,20000.0,20000.0,36 months,8.49,631.26,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
8,68466926,NaN,10000.0,10000.0,10000.0,36 months,6.49,306.45,A,A2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
9,68616873,NaN,8000.0,8000.0,8000.0,36 months,11.48,263.74,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
#4a Are there any missing values? NaN? How many?
print("isnull")
print(data_train.isnull().sum())
print("isna")
print(data_train.isna().sum())

#4b Number of unique values? 
print("isunique")
print(data_train.nunique())

isnull
id                                                  0
member_id                                     2260701
loan_amnt                                          33
funded_amnt                                        33
funded_amnt_inv                                    33
term                                               33
int_rate                                           33
installment                                        33
grade                                              33
sub_grade                                          33
emp_title                                      167002
emp_length                                     146940
home_ownership                                     33
annual_inc                                         37
verification_status                                33
issue_d                                            33
loan_status                                        33
pymnt_plan                                         33
url                                                33
desc                                          2134634
purpose                                            33
title                                           23358
zip_code                                           34
addr_state                                         33
dti                                              1744
delinq_2yrs                                        62
earliest_cr_line                                   62
fico_range_low                                     33
fico_range_high                                    33
inq_last_6mths                                     63
                                               ...
sec_app_open_acc                              2152680
sec_app_revol_util                            2154517
sec_app_open_act_il                           2152680
sec_app_num_rev_accts                         2152680
sec_app_chargeoff_within_12_mths              2152680
sec_app_collections_12_mths_ex_med            2152680
sec_app_mths_since_last_major_derog           2224759
hardship_flag                                      33
hardship_type                                 2249784
hardship_reason                               2249784
hardship_status                               2249784
deferral_term                                 2249784
hardship_amount                               2249784
hardship_start_date                           2249784
hardship_end_date                             2249784
payment_plan_start_date                       2249784
hardship_length                               2249784
hardship_dpd                                  2249784
hardship_loan_status                          2249784
orig_projected_additional_accrued_interest    2252050
hardship_payoff_balance_amount                2249784
hardship_last_payment_amount                  2249784
disbursement_method                                33
debt_settlement_flag                               33
debt_settlement_flag_date                     2226455
settlement_status                             2226455
settlement_date                               2226455
settlement_amount                             2226455
settlement_percentage                         2226455
settlement_term                               2226455
Length: 151, dtype: int64
isna
id                                                  0
member_id                                     2260701
loan_amnt                                          33
funded_amnt                                        33
funded_amnt_inv                                    33
term                                               33
int_rate                                           33
installment                                        33
grade                                              33
sub_grade                                          33
emp_title                                      167002
emp_length                                     146940
home_ownership                                     33
annual_inc                                         37
verification_status                                33
issue_d                                            33
loan_status                                        33
pymnt_plan                                         33
url                                                33
desc                                          2134634
purpose                                            33
title                                           23358
zip_code                                           34
addr_state                                         33
dti                                              1744
delinq_2yrs                                        62
earliest_cr_line                                   62
fico_range_low                                     33
fico_range_high                                    33
inq_last_6mths                                     63
                                               ...
sec_app_open_acc                              2152680
sec_app_revol_util                            2154517
sec_app_open_act_il                           2152680
sec_app_num_rev_accts                         2152680
sec_app_chargeoff_within_12_mths              2152680
sec_app_collections_12_mths_ex_med            2152680
sec_app_mths_since_last_major_derog           2224759
hardship_flag                                      33
hardship_type                                 2249784
hardship_reason                               2249784
hardship_status                               2249784
deferral_term                                 2249784
hardship_amount                               2249784
hardship_start_date                           2249784
hardship_end_date                             2249784
payment_plan_start_date                       2249784
hardship_length                               2249784
hardship_dpd                                  2249784
hardship_loan_status                          2249784
orig_projected_additional_accrued_interest    2252050
hardship_payoff_balance_amount                2249784
hardship_last_payment_amount                  2249784
disbursement_method                                33
debt_settlement_flag                               33
debt_settlement_flag_date                     2226455
settlement_status                             2226455
settlement_date                               2226455
settlement_amount                             2226455
settlement_percentage                         2226455
settlement_term                               2226455
Length: 151, dtype: int64
isunique
id                                            2260701
member_id                                           0
loan_amnt                                        1572
funded_amnt                                      1572
funded_amnt_inv                                 10057
term                                                2
int_rate                                          673
installment                                     93301
grade                                               7
sub_grade                                          35
emp_title                                      512694
emp_length                                         11
home_ownership                                      6
annual_inc                                      89368
verification_status                                 3
issue_d                                           139
loan_status                                         9
pymnt_plan                                          2
url                                           2260668
desc                                           124501
purpose                                            14
title                                           63155
zip_code                                          956
addr_state                                         51
dti                                             10845
delinq_2yrs                                        37
earliest_cr_line                                  754
fico_range_low                                     48
fico_range_high                                    48
inq_last_6mths                                     28
                                               ...
sec_app_open_acc                                   67
sec_app_revol_util                               1216
sec_app_open_act_il                                40
sec_app_num_rev_accts                              86
sec_app_chargeoff_within_12_mths                   22
sec_app_collections_12_mths_ex_med                 18
sec_app_mths_since_last_major_derog               140
hardship_flag                                       2
hardship_type                                       1
hardship_reason                                     9
hardship_status                                     3
deferral_term                                       1
hardship_amount                                  9162
hardship_start_date                                27
hardship_end_date                                  28
payment_plan_start_date                            27
hardship_length                                     1
hardship_dpd                                       34
hardship_loan_status                                5
orig_projected_additional_accrued_interest       7487
hardship_payoff_balance_amount                  10893
hardship_last_payment_amount                     9045
disbursement_method                                 2
debt_settlement_flag                                2
debt_settlement_flag_date                          83
settlement_status                                   3
settlement_date                                    90
settlement_amount                               21941
settlement_percentage                            2070
settlement_term                                    40
Length: 151, dtype: int64

In [3]:
#5 The first column (Loan_ID) is not informative to our task. So let's drop it!
data_train=data_train.drop(['id'],axis=1)
data_train=data_train.drop(['member_id'],axis=1)
data_train=data_train.drop(['desc'],axis=1)
data_train=data_train.drop(['sec_app_open_acc'],axis=1)
data_train=data_train.drop(['sec_app_revol_util'],axis=1)
data_train=data_train.drop(['sec_app_open_act_il'],axis=1)
data_train=data_train.drop(['sec_app_num_rev_accts'],axis=1)
data_train=data_train.drop(['sec_app_chargeoff_within_12_mths'],axis=1)
data_train=data_train.drop(['sec_app_collections_12_mths_ex_med'],axis=1)
data_train=data_train.drop(['sec_app_mths_since_last_major_derog'],axis=1)
data_train=data_train.drop(['hardship_type'],axis=1)
data_train=data_train.drop(['hardship_reason'],axis=1)
data_train=data_train.drop(['hardship_status'],axis=1)
data_train=data_train.drop(['deferral_term'],axis=1)
data_train=data_train.drop(['hardship_amount'],axis=1)
data_train=data_train.drop(['hardship_start_date'],axis=1)
data_train=data_train.drop(['hardship_end_date'],axis=1)
data_train=data_train.drop(['payment_plan_start_date'],axis=1)
data_train=data_train.drop(['hardship_length'],axis=1)
data_train=data_train.drop(['hardship_dpd'],axis=1)
data_train=data_train.drop(['hardship_loan_status'],axis=1)
data_train=data_train.drop(['orig_projected_additional_accrued_interest'],axis=1)
data_train=data_train.drop(['hardship_payoff_balance_amount'],axis=1)
data_train=data_train.drop(['hardship_last_payment_amount'],axis=1)
data_train=data_train.drop(['debt_settlement_flag_date'],axis=1)
data_train=data_train.drop(['settlement_status'],axis=1)
data_train=data_train.drop(['settlement_date'],axis=1)
data_train=data_train.drop(['settlement_amount'],axis=1)
data_train=data_train.drop(['settlement_percentage'],axis=1)
data_train=data_train.drop(['settlement_term'],axis=1)
data_train=data_train.drop(['revol_bal_joint'],axis=1)
data_train=data_train.drop(['sec_app_fico_range_low'],axis=1)
data_train=data_train.drop(['sec_app_fico_range_high'],axis=1)
data_train=data_train.drop(['sec_app_earliest_cr_line'],axis=1)
data_train=data_train.drop(['sec_app_inq_last_6mths'],axis=1)
data_train=data_train.drop(['sec_app_mort_acc'],axis=1)
data_train=data_train.drop(['annual_inc_joint'],axis=1)
data_train=data_train.drop(['dti_joint'],axis=1)
data_train=data_train.drop(['verification_status_joint'],axis=1)
data_train.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,...,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag
0,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,...,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,N,Cash,N
1,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,...,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,N,Cash,N
2,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,...,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,N,Cash,N
3,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,...,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0,N,Cash,N
4,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,...,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,N,Cash,N

In [4]:
#4a Are there any missing values? NaN? How many?
print("isnull")
print(data_train.isnull().sum())
print("isna")
print(data_train.isna().sum())

#4b Number of unique values? 
print("isunique")
print(data_train.nunique())

isnull
loan_amnt                              33
funded_amnt                            33
funded_amnt_inv                        33
term                                   33
int_rate                               33
installment                            33
grade                                  33
sub_grade                              33
emp_title                          167002
emp_length                         146940
home_ownership                         33
annual_inc                             37
verification_status                    33
issue_d                                33
loan_status                            33
pymnt_plan                             33
url                                    33
purpose                                33
title                               23358
zip_code                               34
addr_state                             33
dti                                  1744
delinq_2yrs                            62
earliest_cr_line                       62
fico_range_low                         33
fico_range_high                        33
inq_last_6mths                         63
mths_since_last_delinq            1158535
mths_since_last_record            1901545
open_acc                               62
                                   ...
mort_acc                            50063
mths_since_recent_bc                73445
mths_since_recent_bc_dlq          1741000
mths_since_recent_inq              295468
mths_since_recent_revol_delinq    1520342
num_accts_ever_120_pd               70309
num_actv_bc_tl                      70309
num_actv_rev_tl                     70309
num_bc_sats                         58623
num_bc_tl                           70309
num_il_tl                           70309
num_op_rev_tl                       70309
num_rev_accts                       70310
num_rev_tl_bal_gt_0                 70309
num_sats                            58623
num_tl_120dpd_2m                   153690
num_tl_30dpd                        70309
num_tl_90g_dpd_24m                  70309
num_tl_op_past_12m                  70309
pct_tl_nvr_dlq                      70464
percent_bc_gt_75                    75412
pub_rec_bankruptcies                 1398
tax_liens                             138
tot_hi_cred_lim                     70309
total_bal_ex_mort                   50063
total_bc_limit                      50063
total_il_high_credit_limit          70309
hardship_flag                          33
disbursement_method                    33
debt_settlement_flag                   33
Length: 112, dtype: int64
isna
loan_amnt                              33
funded_amnt                            33
funded_amnt_inv                        33
term                                   33
int_rate                               33
installment                            33
grade                                  33
sub_grade                              33
emp_title                          167002
emp_length                         146940
home_ownership                         33
annual_inc                             37
verification_status                    33
issue_d                                33
loan_status                            33
pymnt_plan                             33
url                                    33
purpose                                33
title                               23358
zip_code                               34
addr_state                             33
dti                                  1744
delinq_2yrs                            62
earliest_cr_line                       62
fico_range_low                         33
fico_range_high                        33
inq_last_6mths                         63
mths_since_last_delinq            1158535
mths_since_last_record            1901545
open_acc                               62
                                   ...
mort_acc                            50063
mths_since_recent_bc                73445
mths_since_recent_bc_dlq          1741000
mths_since_recent_inq              295468
mths_since_recent_revol_delinq    1520342
num_accts_ever_120_pd               70309
num_actv_bc_tl                      70309
num_actv_rev_tl                     70309
num_bc_sats                         58623
num_bc_tl                           70309
num_il_tl                           70309
num_op_rev_tl                       70309
num_rev_accts                       70310
num_rev_tl_bal_gt_0                 70309
num_sats                            58623
num_tl_120dpd_2m                   153690
num_tl_30dpd                        70309
num_tl_90g_dpd_24m                  70309
num_tl_op_past_12m                  70309
pct_tl_nvr_dlq                      70464
percent_bc_gt_75                    75412
pub_rec_bankruptcies                 1398
tax_liens                             138
tot_hi_cred_lim                     70309
total_bal_ex_mort                   50063
total_bc_limit                      50063
total_il_high_credit_limit          70309
hardship_flag                          33
disbursement_method                    33
debt_settlement_flag                   33
Length: 112, dtype: int64
isunique
loan_amnt                            1572
funded_amnt                          1572
funded_amnt_inv                     10057
term                                    2
int_rate                              673
installment                         93301
grade                                   7
sub_grade                              35
emp_title                          512694
emp_length                             11
home_ownership                          6
annual_inc                          89368
verification_status                     3
issue_d                               139
loan_status                             9
pymnt_plan                              2
url                               2260668
purpose                                14
title                               63155
zip_code                              956
addr_state                             51
dti                                 10845
delinq_2yrs                            37
earliest_cr_line                      754
fico_range_low                         48
fico_range_high                        48
inq_last_6mths                         28
mths_since_last_delinq                173
mths_since_last_record                129
open_acc                               91
                                   ...
mort_acc                               47
mths_since_recent_bc                  546
mths_since_recent_bc_dlq              177
mths_since_recent_inq                  26
mths_since_recent_revol_delinq        179
num_accts_ever_120_pd                  44
num_actv_bc_tl                         42
num_actv_rev_tl                        57
num_bc_sats                            60
num_bc_tl                              76
num_il_tl                             122
num_op_rev_tl                          81
num_rev_accts                         117
num_rev_tl_bal_gt_0                    50
num_sats                               91
num_tl_120dpd_2m                        7
num_tl_30dpd                            5
num_tl_90g_dpd_24m                     34
num_tl_op_past_12m                     33
pct_tl_nvr_dlq                        690
percent_bc_gt_75                      284
pub_rec_bankruptcies                   12
tax_liens                              42
tot_hi_cred_lim                    529972
total_bal_ex_mort                  212777
total_bc_limit                      20309
total_il_high_credit_limit         194137
hardship_flag                           2
disbursement_method                     2
debt_settlement_flag                    2
Length: 112, dtype: int64

In [21]:
#drop needed columns
data_train=data_train.drop(['loan_amnt'],axis=1)
data_train=data_train.drop(['funded_amnt'],axis=1)
data_train=data_train.drop(['funded_amnt_inv'],axis=1)
data_train=data_train.drop(['term'],axis=1)
data_train=data_train.drop(['int_rate'],axis=1)
data_train=data_train.drop(['installment'],axis=1)
data_train=data_train.drop(['grade'],axis=1)
data_train=data_train.drop(['sub_grade'],axis=1)
data_train=data_train.drop(['home_ownership'],axis=1)
data_train=data_train.drop(['annual_inc'],axis=1)
data_train=data_train.drop(['verification_status'],axis=1)
data_train=data_train.drop(['issue_d'],axis=1)
data_train=data_train.drop(['loan_status'],axis=1)
data_train=data_train.drop(['pymnt_plan'],axis=1)
data_train=data_train.drop(['url'],axis=1)
data_train=data_train.drop(['purpose'],axis=1)
data_train=data_train.drop(['zip_code'],axis=1)
data_train=data_train.drop(['addr_state'],axis=1)
data_train=data_train.drop(['delinq_2yrs'],axis=1)
data_train=data_train.drop(['earliest_cr_line'],axis=1)
data_train=data_train.drop(['fico_range_low'],axis=1)
data_train=data_train.drop(['fico_range_high'],axis=1)
data_train=data_train.drop(['inq_last_6mths'],axis=1)
data_train=data_train.drop(['open_acc'],axis=1)
data_train=data_train.drop(['pub_rec'],axis=1)
data_train=data_train.drop(['total_acc'],axis=1)
data_train=data_train.drop(['initial_list_status'],axis=1)
data_train=data_train.drop(['out_prncp'],axis=1)
data_train=data_train.drop(['out_prncp_inv'],axis=1)
data_train=data_train.drop(['total_pymnt'],axis=1)
data_train=data_train.drop(['total_rec_prncp'],axis=1)
data_train=data_train.drop(['total_rec_int'],axis=1)
data_train=data_train.drop(['total_rec_late_fee'],axis=1)
data_train=data_train.drop(['recoveries'],axis=1)
data_train=data_train.drop(['collection_recovery_fee'],axis=1)
data_train=data_train.drop(['last_pymnt_amnt'],axis=1)
data_train=data_train.drop(['last_fico_range_high'],axis=1)
data_train=data_train.drop(['last_fico_range_low'],axis=1)
data_train=data_train.drop(['policy_code'],axis=1)
data_train=data_train.drop(['application_type'],axis=1)
data_train=data_train.drop(['total_pymnt_inv'],axis=1)
data_train=data_train.drop(['hardship_flag'],axis=1)
data_train=data_train.drop(['disbursement_method'],axis=1)
data_train=data_train.drop(['debt_settlement_flag'],axis=1)
data_train.head()

KeyError: "['loan_amnt'] not found in axis"

In [19]:
#4a Are there any missing values? NaN? How many?
print("isnull")
print(data_train.isnull().sum())
print("isna")
print(data_train.isna().sum())

#4b Number of unique values? 
print("isunique")
print(data_train.nunique())

isnull
emp_title                          167002
emp_length                         146940
title                               23358
dti                                  1744
mths_since_last_delinq            1158535
mths_since_last_record            1901545
revol_bal                              33
revol_util                           1835
last_pymnt_d                         2460
next_pymnt_d                      1345343
last_credit_pull_d                    105
collections_12_mths_ex_med            178
mths_since_last_major_derog       1679926
acc_now_delinq                         62
tot_coll_amt                        70309
tot_cur_bal                         70309
open_acc_6m                        866163
open_act_il                        866162
open_il_12m                        866162
open_il_24m                        866162
mths_since_rcnt_il                 909957
total_bal_il                       866162
il_util                           1068883
open_rv_12m                        866162
open_rv_24m                        866162
max_bal_bc                         866162
all_util                           866381
total_rev_hi_lim                    70309
inq_fi                             866162
total_cu_tl                        866163
                                   ...
mo_sin_old_rev_tl_op                70310
mo_sin_rcnt_rev_tl_op               70310
mo_sin_rcnt_tl                      70309
mort_acc                            50063
mths_since_recent_bc                73445
mths_since_recent_bc_dlq          1741000
mths_since_recent_inq              295468
mths_since_recent_revol_delinq    1520342
num_accts_ever_120_pd               70309
num_actv_bc_tl                      70309
num_actv_rev_tl                     70309
num_bc_sats                         58623
num_bc_tl                           70309
num_il_tl                           70309
num_op_rev_tl                       70309
num_rev_accts                       70310
num_rev_tl_bal_gt_0                 70309
num_sats                            58623
num_tl_120dpd_2m                   153690
num_tl_30dpd                        70309
num_tl_90g_dpd_24m                  70309
num_tl_op_past_12m                  70309
pct_tl_nvr_dlq                      70464
percent_bc_gt_75                    75412
pub_rec_bankruptcies                 1398
tax_liens                             138
tot_hi_cred_lim                     70309
total_bal_ex_mort                   50063
total_bc_limit                      50063
total_il_high_credit_limit          70309
Length: 68, dtype: int64
isna
emp_title                          167002
emp_length                         146940
title                               23358
dti                                  1744
mths_since_last_delinq            1158535
mths_since_last_record            1901545
revol_bal                              33
revol_util                           1835
last_pymnt_d                         2460
next_pymnt_d                      1345343
last_credit_pull_d                    105
collections_12_mths_ex_med            178
mths_since_last_major_derog       1679926
acc_now_delinq                         62
tot_coll_amt                        70309
tot_cur_bal                         70309
open_acc_6m                        866163
open_act_il                        866162
open_il_12m                        866162
open_il_24m                        866162
mths_since_rcnt_il                 909957
total_bal_il                       866162
il_util                           1068883
open_rv_12m                        866162
open_rv_24m                        866162
max_bal_bc                         866162
all_util                           866381
total_rev_hi_lim                    70309
inq_fi                             866162
total_cu_tl                        866163
                                   ...
mo_sin_old_rev_tl_op                70310
mo_sin_rcnt_rev_tl_op               70310
mo_sin_rcnt_tl                      70309
mort_acc                            50063
mths_since_recent_bc                73445
mths_since_recent_bc_dlq          1741000
mths_since_recent_inq              295468
mths_since_recent_revol_delinq    1520342
num_accts_ever_120_pd               70309
num_actv_bc_tl                      70309
num_actv_rev_tl                     70309
num_bc_sats                         58623
num_bc_tl                           70309
num_il_tl                           70309
num_op_rev_tl                       70309
num_rev_accts                       70310
num_rev_tl_bal_gt_0                 70309
num_sats                            58623
num_tl_120dpd_2m                   153690
num_tl_30dpd                        70309
num_tl_90g_dpd_24m                  70309
num_tl_op_past_12m                  70309
pct_tl_nvr_dlq                      70464
percent_bc_gt_75                    75412
pub_rec_bankruptcies                 1398
tax_liens                             138
tot_hi_cred_lim                     70309
total_bal_ex_mort                   50063
total_bc_limit                      50063
total_il_high_credit_limit          70309
Length: 68, dtype: int64
isunique
emp_title                         512694
emp_length                            11
title                              63155
dti                                10845
mths_since_last_delinq               173
mths_since_last_record               129
revol_bal                         102251
revol_util                          1430
last_pymnt_d                         136
next_pymnt_d                         106
last_credit_pull_d                   141
collections_12_mths_ex_med            16
mths_since_last_major_derog          183
acc_now_delinq                         9
tot_coll_amt                       15574
tot_cur_bal                       487688
open_acc_6m                           19
open_act_il                           54
open_il_12m                           19
open_il_24m                           31
mths_since_rcnt_il                   405
total_bal_il                      162249
il_util                              280
open_rv_12m                           29
open_rv_24m                           50
max_bal_bc                         33726
all_util                             188
total_rev_hi_lim                   34220
inq_fi                                33
total_cu_tl                           62
                                   ...
mo_sin_old_rev_tl_op                 787
mo_sin_rcnt_rev_tl_op                333
mo_sin_rcnt_tl                       232
mort_acc                              47
mths_since_recent_bc                 546
mths_since_recent_bc_dlq             177
mths_since_recent_inq                 26
mths_since_recent_revol_delinq       179
num_accts_ever_120_pd                 44
num_actv_bc_tl                        42
num_actv_rev_tl                       57
num_bc_sats                           60
num_bc_tl                             76
num_il_tl                            122
num_op_rev_tl                         81
num_rev_accts                        117
num_rev_tl_bal_gt_0                   50
num_sats                              91
num_tl_120dpd_2m                       7
num_tl_30dpd                           5
num_tl_90g_dpd_24m                    34
num_tl_op_past_12m                    33
pct_tl_nvr_dlq                       690
percent_bc_gt_75                     284
pub_rec_bankruptcies                  12
tax_liens                             42
tot_hi_cred_lim                   529972
total_bal_ex_mort                 212777
total_bc_limit                     20309
total_il_high_credit_limit        194137
Length: 68, dtype: int64